# Generated by Django 4.2 on 2026-07-16 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free Tier'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('max_storage', models.BigIntegerField()),
                ('max_file_size', models.BigIntegerField()),
                ('max_retention_days', models.IntegerField()),
                ('concurrent_uploads', models.IntegerField(default=5)),
                ('current_usage', models.BigIntegerField(default=0)),
                ('allow_password_protection', models.BooleanField(default=False)),
                ('allow_expiry', models.BooleanField(default=False)),
                ('allow_download_tracking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Storage Quotas',
            },
        ),
        migrations.CreateModel(
            name='RateLimitExceeded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=200)),
                ('attempts', models.IntegerField(default=1)),
                ('first_attempt', models.DateTimeField(auto_now_add=True)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('password', 'Password Protected')], default='private', max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_delete', models.BooleanField(default=False)),
                ('storage_backend', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'AWS S3')], default='local', max_length=20)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('download_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('scan_result', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('downloader_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='fileshare.fileupload')),
            ],
        ),
        migrations.AddIndex(
            model_name='ratelimitexceeded',
            index=models.Index(fields=['ip_address', 'endpoint'], name='fileshare_r_ip_addr_b8de7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimitexceeded',
            unique_together={('user', 'ip_address', 'endpoint')},
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['owner', 'created_at'], name='fileshare_f_owner_i_33b4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['access_token'], name='fileshare_f_access__bfe616_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_hash'], name='fileshare_f_file_ha_b25061_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['expires_at'], name='fileshare_f_expires_89d2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['file', 'downloaded_at'], name='fileshare_d_file_id_1f1712_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['downloader_ip'], name='fileshare_d_downloa_c0cb44_idx'),
        ),
    ]
